// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BinaryDefense.FSharp.Analyzers.Tests")>]
[<assembly: AssemblyProductAttribute("BinaryDefense.FSharp.Analyzers")>]
[<assembly: AssemblyVersionAttribute("0.2.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-05-23T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.2.2")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","ce6714e40c39d4a88cba9b4cbe0b5f93e2c1b285")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BinaryDefense.FSharp.Analyzers.Tests"
    let [<Literal>] AssemblyProduct = "BinaryDefense.FSharp.Analyzers"
    let [<Literal>] AssemblyVersion = "0.2.2"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-05-23T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.2.2"
    let [<Literal>] AssemblyInformationalVersion = "0.2.2"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "ce6714e40c39d4a88cba9b4cbe0b5f93e2c1b285"
