// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BinaryDefense.FSharp.Analyzers.Tests")>]
[<assembly: AssemblyProductAttribute("BinaryDefense.FSharp.Analyzers")>]
[<assembly: AssemblyVersionAttribute("0.2.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-01-21T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.2.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","beta")>]
[<assembly: AssemblyMetadataAttribute("GitHash","90501ea314dd4160f3ba158365e8c428243d1710")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BinaryDefense.FSharp.Analyzers.Tests"
    let [<Literal>] AssemblyProduct = "BinaryDefense.FSharp.Analyzers"
    let [<Literal>] AssemblyVersion = "0.2.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-01-21T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.2.1"
    let [<Literal>] AssemblyInformationalVersion = "0.2.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "beta"
    let [<Literal>] AssemblyMetadata_GitHash = "90501ea314dd4160f3ba158365e8c428243d1710"
