// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("hashing")>]
[<assembly: AssemblyProductAttribute("BinaryDefense.FSharp.Analyzers")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-03-26T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","791957f2ad776d41ac920184b1d51151352f62ac")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "hashing"
    let [<Literal>] AssemblyProduct = "BinaryDefense.FSharp.Analyzers"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-03-26T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "791957f2ad776d41ac920184b1d51151352f62ac"
