// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("hashing")>]
[<assembly: AssemblyProductAttribute("BinaryDefense.FSharp.Analyzers")>]
[<assembly: AssemblyVersionAttribute("0.2.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-01-21T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.2.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","85c69689a2c555beda673c375d6d97032c192df9")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "hashing"
    let [<Literal>] AssemblyProduct = "BinaryDefense.FSharp.Analyzers"
    let [<Literal>] AssemblyVersion = "0.2.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-01-21T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.2.1"
    let [<Literal>] AssemblyInformationalVersion = "0.2.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "85c69689a2c555beda673c375d6d97032c192df9"
