// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("hashing")>]
[<assembly: AssemblyProductAttribute("BinaryDefense.FSharp.Analyzers")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-03-30T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","beta")>]
[<assembly: AssemblyMetadataAttribute("GitHash","1b54b70d6e5218fdbe3cf92cae4cf76f1154c8e9")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "hashing"
    let [<Literal>] AssemblyProduct = "BinaryDefense.FSharp.Analyzers"
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-03-30T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
    let [<Literal>] AssemblyInformationalVersion = "0.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "beta"
    let [<Literal>] AssemblyMetadata_GitHash = "1b54b70d6e5218fdbe3cf92cae4cf76f1154c8e9"
